server:
  port: 83
spring:
  application:
    name: cloud-consumer-order
  cloud:
    # consul
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
web:
  swagger:
    enabled: true